import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'


const majalla = localFont({
  src: [{ path: './majallar.ttf', weight: '400', style: 'normal' }, {
    path: "./majallab.ttf", weight: "700", style: 'normal'
    ,
  },],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir='rtl'>
      <body className={majalla.className}>{children}</body>
    </html>
  )
}
